# Generated by Django 3.1.1 on 2021-06-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0003_auto_20210615_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ORM.department'),
        ),
    ]
